In [104]:
#import libraries

In [105]:
import numpy as np

In [106]:
import pandas as pd

In [107]:
import matplotlib.pyplot as plt

In [108]:
#importing dataset

In [109]:
dataset = pd.read_csv('Data.csv')

In [110]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [111]:
X = dataset.iloc[:, :3].values

In [112]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [113]:
Y = dataset.iloc[:, 3].values

In [114]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [115]:
#missing data

In [116]:
from sklearn.impute import SimpleImputer

In [117]:
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')

In [118]:
imputer = imputer.fit(X[:, 1:3])

In [119]:
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [120]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [121]:
#categorical data

In [122]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [123]:
labelEncoder_X = LabelEncoder()

In [124]:
X[:, 0] = labelEncoder_X.fit_transform(X[:, 0])

In [125]:
ct = ColumnTransformer([("Country", OneHotEncoder(), [0])], remainder = 'passthrough')

In [126]:
X = ct.fit_transform(X)

In [127]:
labelEncoder_Y = LabelEncoder()

In [128]:
Y = labelEncoder_Y.fit_transform(Y)

In [129]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [130]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [131]:
#splitting into test train dataset

In [132]:
from sklearn.model_selection import train_test_split

In [133]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [134]:
X_train

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778]], dtype=object)

In [135]:
#feature scalling

In [136]:
from sklearn.preprocessing import StandardScaler

In [137]:
sc_X = StandardScaler()

In [138]:
X_train = sc_X.fit_transform(X_train)

In [139]:
X_test = sc_X.transform(X_test)

In [140]:
X_train

array([[-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934],
       [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479]])